# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/Users/tony/arc/pro/dev/svdev/rv32core/zybo/zybo.runs/synth_1/microprocessor.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-1518-xiluntu/incrSyn
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /Users/tony/arc/pro/dev/svdev/rv32core/zybo/zybo.cache/wt [current_project]
set_property parent.project_path /Users/tony/arc/pro/dev/svdev/rv32core/zybo/zybo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/tony/.Xilinx/Vivado/2024.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo /Users/tony/arc/pro/dev/svdev/rv32core/zybo/zybo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem /Users/tony/arc/pro/dev/svdev/rv32core/src-old/instr.mem
read_verilog -library xil_defaultlib -sv {
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/adder.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/alu.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/branch.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/control_decoder.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/control_unit.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/core.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/data_mem.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/immediategen.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/instr_mem.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/memory.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/memory_wrapper.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/mux.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/mux2_4.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/mux3_8.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/pc.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/register_file.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/stage_decode.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/stage_execute.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/stage_fetch.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/stage_memory.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/stage_writeback.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/type_decoder.sv
  /Users/tony/arc/pro/dev/svdev/rv32core/src-old/microprocessor.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top microprocessor -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef microprocessor.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file microprocessor_utilization_synth.rpt -pb microprocessor_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
