#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Dec 15 11:39:25 +0530 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_microprocessor_behav -key {Behavioral:sim_1:Functional:tb_microprocessor} -tclbatch tb_microprocessor.tcl -log simulate.log"
xsim tb_microprocessor_behav -key {Behavioral:sim_1:Functional:tb_microprocessor} -tclbatch tb_microprocessor.tcl -log simulate.log

